array:
  type: "TASD" # or "CBSD"

data:
  # data paths
  mc_file: '/data/tlfptn_1850.all.tlsdfit.result.parquet' # or '/data/tlfptn_1850.tlsdfit.result.parquet'
  dt_file: '/data/sddt.main.result.parquet' # or '/data/sddt.cb.noCuts.result.parquet'

energy:
  bins: [18.0, 18.1, 18.2, 18.3, 18.4, 18.5,
         18.6, 18.7, 18.8, 18.9, 19.0, 19.1,
         19.2, 19.3, 19.4, 19.5, 19.6,
         19.8, 20.0, 20.3]

geometry:
  generated_area_m2: 1.96349541e9 # Generated area (Dmitri's thesis) in meters squared: π (25 km)^2
  generated_solid_angle_sr: 2.35619449 # Generated solid angle (Dmitri's thesis): 3π/4

run:
  time_s: 504921600 # 16 years in seconds

plotting:
  output_dir: "/output/plots"